browser: "phantomjs"
browser_executable: "/usr/local/bin/phantomjs"

directory: "enso"

domains:
  base: "http://www.decorex.com/uk"
  compare: "http://www.cphi.com/europe"

workers: 8

screen_widths:
  - 320
  - 1280

paths_file: "paths.txt"

spider_skips:
  - "^/ajax/.*"
  - "^/calendar/ical/.*"

reports:
  thumbnail_width: 300
  thumbnail_height: 200
