browser: "phantomjs"

directory: "enso"

domains:
  base: "http://www.decorex.com/uk"
  compare: "http://www.cphi.com/europe"

workers: 4

screen_widths:
  - 320
  - 1280

spider_file: "paths.txt"

spider_skips:
  - /ajax/.*

#paths:
#  home: /
#  exhibitors: /exhibitors
#  agenda: /agenda
#  exhibit: /exhibit
