browser: "phantomjs"
driver_executable: "/usr/local/bin/phantomjs"

directory: "enso"

domains:
  base: "http://webserver.dev/enso"
  compare: "http://webserver.dev/dev"

workers: 4

screen_widths:
  - 320
  - 1280

paths_file: "paths_simple.txt"

spider_skips:
  - "^/ajax/.*"
  - "^/calendar/ical/.*"

reports:
  thumbnail_width: 300
  thumbnail_height: 200
