browser_name: "phantomjs"
driver_executable: "/usr/local/bin/phantomjs"

# selenium grid example
#browse_name: "firefox"
#browser_version: 53
#remote_address: "http://localhost:4444/wd/hub"

directory: "shots"
history_directory: "shots_history"

domains:
  base: "http://webserver.dev/enso"
  compare: "http://webserver.dev/dev"

workers: 4

screen_widths:
  - 320
  - 1280

paths_file: "paths_simple.txt"

spider_skips:
  - "^/ajax/.*"
  - "^/calendar/ical/.*"

multiple_browsers:
  - browser_label: "Firefox last"
    browser_name: "firefox"
    driver_executable: "/usr/local/bin/geckodriver"
  - browser_label: "Chrome last"
    browser_name: "chrome"
    driver_executable: "/usr/local/bin/chromedriver"
    
# selenium grid example
#
#multibrowser:
#  - label: "Firefox 53 Linux"
#    browser: "firefox"
#    browser_version: 53
#    remote_address: "http://localhost:4444/wd/hub"
#  - label: "Chrome last"
#    browser: "chrome"
#    browser_version: 58
#    remote_address: "http://localhost:4444/wd/hub"

reports:
  threshold: 15
  thumbnail_width: 300
  thumbnail_height: 300
