browser: "phantomjs"

directory: "enso"

domains:
  base: "http://webserver.dev/enso"
  compare: "http://webserver.dev/dev"

workers: 4

screen_widths:
  - 320
  - 1280

spider_file: "paths.txt"

spider_skips:
  - "^/ajax/.*"
  - "^/calendar/ical/.*"

#paths:
#  home: /
#  exhibitors: /exhibitors
#  agenda: /agenda
#  exhibit: /exhibit
